name: ArtCon_Front CI

env:
  main_project_module: app

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set current date as env variable
      run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Set repository name as env variable
      run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Verify with Gradle
      run: ./gradlew check

    - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
      run: ./gradlew assembleDebug


    - name: Build app bundle debug (AAB) - ${{ env.main_project_module }} module
      run: ./gradlew bundleDebug

    - name: Build apk release project (APK) - ${{ env.main_project_module }} module
      run: ./gradlew assembleRelease


    - name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
      run: ./gradlew bundleRelease

    - name: Archive Debug APKs
      uses: actions/upload-artifact@v3.1.3
      with:
        name: apk-debug
        path: app/build/outputs/apk/debug/

    - name: Archive Debug AABs
      uses: actions/upload-artifact@v3.1.3
      with:
        name: aab-debug
        path: app/build/outputs/bundle/debug/

    - name: Archive Release APKs
      uses: actions/upload-artifact@v3.1.3
      with:
        name: apk-release
        path: app/build/outputs/apk/release/

    - name: Archive Release APKs
      uses: actions/upload-artifact@v3.1.3
      with:
        name: aab-release
        path: app/build/outputs/bundle/release/
